objects/Attendee__c.object
<CustomObject>
    <description>The recorded list of all the possible attendees for the event.</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <description>The recorded date and time of which when the event will end.</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to determine if the recorded event is currently live or not.</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>The maximum capacity of the recorded event.</description>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>The recorded time and date of which when the event will start.</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>The list of the Attendees going to an Event.</description>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays all the Events that are available for Attendees.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>The assigned speaker for an event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>The event in which a speaker will talk.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>The speaker who is available to talk in an event.</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventDetailsController_Test.cls
@IsTest
private class EventDetailsController_Test {
    
    static Id createTestEvent(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Start__c = datetime.newInstance(2021, 7, 21, 19, 30, 0);
        evt.End__c = datetime.newInstance(2021, 7, 22, 20, 30, 0);
        evt.Max_Seats__c = 10;
        insert evt;
        return evt.Id;
    }
    static Id createTestSpeaker(){
        Speaker__c spk = new Speaker__c();
        spk.Name = 'Test Spek';
        insert spk;
        return spk.Id;
    }
    static Id createTestAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee';
        insert att;
        return att.Id;
    }
    @IsTest
    static void testSpeaker(){
        
        Test.startTest();
        String recId;
        Event_Speaker__c eS = new Event_Speaker__c();
        eS.Event__c = createTestEvent();
        eS.Speaker__c = createTestSpeaker();
        eS.Name = 'Test Name';
        Event_Speaker__c name;
        String str = '';
        insert eS;
        List<Event_Speaker__c> retrievedSpeaker = EventDetailsController.getSpeakers(eS.Event__c);
        //Event_Speaker__c acquiredSpeaker = [SELECT Id,Name FROM Event_Speaker__c];
        name = retrievedSpeaker.get(0);
        Test.stopTest();
        System.assertEquals('Test Name',name.Name);
    }
    @IsTest
    static void testLocation(){
        Test.startTest();
        String recId = createTestEvent();
        Event__c evts = EventDetailsController.getLocationDetails(recId);
        Test.stopTest();
        System.assertEquals('Test Event',evts.Name);
    }
    @isTest
    static void testAttendee(){
        Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        eA.Attendee__c = createTestAttendee();
        eA.Event__c = createTestEvent();
        eA.Name = 'Test EA';
        insert eA;
        Event_Attendee__c name;
        List<Event_Attendee__c> retrievedAttendee = EventDetailsController.getAttendees(eA.Event__c);
        name = retrievedAttendee.get(0);
        
        Test.stopTest();
        System.assertEquals('Test EA', name.Name);
    }
}