objects/Attendee__c.object
<CustomObject>
    <description>The recorded list of all the possible attendees for the event.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>The recorded email of the attendee.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location_Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The address of the attendee based on Location (Address Book) object.</description>
        <label>Location (Address Book)</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The recorded event organizer responsible for the event.</description>
        <label>Event Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This field determines if the event recorded is a personal type of event or a virtual type of event.</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Location_Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The location of the recorded event.</description>
        <label>Location (Address Book)</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>The recorded time and date of which when the event will start.</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>The list of the Attendees going to an Event.</description>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays all the Events that are available for Attendees.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Organizer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Recorded email of the event organizer.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location_Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The recorded address of the event organizer based on Location (Address book) field.</description>
        <label>Location (Address Book)</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizer_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>Location or Address book of all the recorded Events using this app.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>The recorded City name for a potential event venue.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>List of all the Countries for a potential event venue.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Côte d&apos;Ivoire</fullName>
                </value>
                <value>
                    <fullName>Cabo Verde</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>The recorded Postal Code of an area that is a potential event venue.</description>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The recorded State name for a potential event venue.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The recorded Street names for a potential event venue.</description>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventAttendeeTrigger.cls
public class EventAttendeeTrigger {

    public static void sendAttendeeEmail(List<Event_Attendee__c> newRecordList ) {
        
        Set<Id> attendeesIdsSet = new Set<Id>();
        Set<Id> eventIdsSet = new Set<Id>();
        
        for(Event_Attendee__c evtAtt : newRecordList){
            attendeesIdsSet.add(evtAtt.Attendee__c);
            eventIdsSet.add(evtAtt.Event__c);
        }
        
        Map<Id,Attendee__c> attendeeMap = new Map<Id,Attendee__c>( 
            [Select Id, Name, Email__c From Attendee__c WHERE  Id IN : attendeesIdsSet]
        );
        Map<Id, Event__c> eventMap = new Map<Id, Event__c > ([Select Id, Name, Start__c, Event_Organizer__c, Event_Type__c, Event_Organizer__r.Name, Location_Address_Book__c , Location_Address_Book__r.Name, Location_Address_Book__r.City__c, Location_Address_Book__r.State__c, Location_Address_Book__r.Country__c, Location_Address_Book__r.Postal_Code__c, Location_Address_Book__r.Street__c FROM Event__c  WHERE ID IN: eventIdsSet]);
        
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        for(Event_Attendee__c evtAtt : newRecordList){
            
            Attendee__c att = attendeeMap.get(evtAtt.Attendee__c);
            Event__c evt = eventMap.get(evtAtt.Event__c);
            
            if(evt.Event_Type__c == 'Virtual'){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                mail.setSubject('Pass for the '+evt.Name);
                List<String> toAddress = new List<String>();
                toAddress.add(att.Email__c);
                mail.setToAddresses( toAddress );
                mail.setSenderDisplayName(evt.Event_Organizer__r.Name);
                
                String virtualLink = 'https://meet.google.com/';
                String hrefForVirtualLink = '<a href="'+virtualLink+'"'+'target="_blank">GMeet Link</a>';
                String emailBody = 'Hello '+ att.Name + ',<br/><br/>'+
                    'Your registration for '+evt.Name+' that will happen on '+
                    evt.Start__c+' has been confirmed. This event will be held at Google Meet.<br/>We are excited to have you!'+ 
                    ' See you at the event. <br/>'+
                    'You can find the link for the said event via this link here: '+hrefForVirtualLink+'.<br/><br/><br/>'+
                    'Thanks,<br/>'+evt.Event_Organizer__r.Name;
                
                mail.setHtmlBody(emailBody);
                emailList.add(mail);
                
            }else{
                 Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

                mail.setSubject('Pass for the '+evt.Name);
                List<String> toAddress = new List<String>();
                toAddress.add(att.Email__c);
                mail.setToAddresses( toAddress );
                mail.setSenderDisplayName(evt.Event_Organizer__r.Name);
                
                String location = 'https://www.google.com/maps/place/'+evt.Location_Address_Book__r.Street__c+' '+evt.Location_Address_Book__r.City__c+' '
                    +evt.Location_Address_Book__r.State__c+' '+
                    evt.Location_Address_Book__r.Country__c+' '+evt.Location_Address_Book__r.Postal_Code__c;
                
                String hrefForLocation = '<a href="'+location+'"'+'target="_blank">GMaps Link</a>';
                
                String emailBody = 'Hello '+ att.Name + ',<br/><br/>'+
                    'Your registration for '+evt.Name+' that will happen on '+
                    evt.Start__c+' has been confirmed. This will be held at '+evt.Location_Address_Book__r.Name
                    +'.<br/>We are excited to have you!'+ 
                    ' See you at the event. <br/>'+
                    'You can find the location for the said event via Google Maps here: '+hrefForLocation+'.<br/><br/><br/>'+
                    'Thanks,<br/>'+evt.Event_Organizer__r.Name;
                
                mail.setHtmlBody(emailBody);
                emailList.add(mail);
            }
        }
        
        try{
            
            List<Messaging.SendEmailResult> results =  Messaging.sendEmail(emailList, false);
            for(Messaging.SendEmailResult email : results){
                System.debug(email.isSuccess());
                if(!email.isSuccess()){
                    List<Messaging.SendEmailError> errors = email.getErrors();
                }
            }  
        }catch(System.Exception ex){
            System.debug(' ' + ex);
        }
    }
}