objects/Attendee__c.object
<CustomObject>
    <description>The recorded list of all the possible attendees for the event.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>The recorded email of the attendee.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>The recorded phone number of the attendee.</description>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <description>The recorded date and time of which when the event will end.</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The recorded event organizer responsible for the event.</description>
        <label>Event Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This field determines if the event recorded is a personal type of event or a virtual type of event.</description>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>This determines if the event is happening on a daily or weekly basis.</description>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to determine if the recorded event is currently live or not.</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>The maximum capacity of the recorded event.</description>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to determine if the recorded event is recurring or not.</description>
        <label>Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>The recorded time and date of which when the event will start.</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>The list of the Attendees going to an Event.</description>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays all the Events that are available for Attendees.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Organizer__c.object
<CustomObject>
    <fields>
        <fullName>Alt_Email__c</fullName>
        <description>The recorded alternative email of the event organizer.</description>
        <label>Alternative Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alt_Phone_Number__c</fullName>
        <description>The recorded alternative phone number of the event organizer.</description>
        <label>Alternative Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Recorded email of the event organizer.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>The recorded phone number of the event organizer.</description>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventAttendeeTrigger_Test.cls
@isTest
public class EventAttendeeTrigger_Test {
    
    @testSetup
    public static void createTestID(){
        
        Event_Organizer__c  org = new Event_Organizer__c (
            Name = 'Test Organizer',
            Phone_Number__c = '9807654321',
            Email__c = 'testorg@email.com',
            Alt_Phone_Number__c  = '6627323',
            Alt_Email__c ='testorganizer@email.com'
        );
        insert org;
        
        Event__c event = new Event__c(
            Name = 'Test Event',
            Event_Organizer__c  = org.Id,
            Event_Type__c = 'Virtual',
            Frequency__c  = 'Daily',
            Max_Seats__c  = 49,
            Recurring__c = true,
            Live__c = true,
            Start__c = System.now(),
            End__c  = System.now().addDays(3)
        );
        insert event;
        Attendee__c att = new Attendee__c(
            Name = 'Test Attendee',
            Email__c = 'testatt@gmail.com',
            Phone_Number__c = '232323'
        );
        insert att;
        
        Event_Attendee__c evtAtt = new Event_Attendee__c(Event__c = event.Id, Attendee__c = att.Id);
        insert evtAtt;
    }
    
    @IsTest
    static void testEmail(){
        
        Test.startTest();
        createTestID();
        List <Event_Attendee__c> evtAtt = [Select Id, Name, Attendee__c, Event__c from Event_Attendee__c];
        EventAttendeeTrigger.sendAttendeeEmail(evtAtt);
        Test.stopTest();
        
    }
}