objects/Error_Log__c.object
<CustomObject>
    <description>Object for error logs in the app</description>
    <fields>
        <fullName>Log_Date_Tile__c</fullName>
        <description>Date &amp; Time details when the Error Occurred</description>
        <label>Log Date/Tile</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log_Details__c</fullName>
        <description>Stores the Complete Stack Track about the Problem</description>
        <label>Log Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>The Name of Either Apex Class or Apex Trigger</description>
        <label>Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ErrorLogGenerator_Test.cls
@isTest
private class ErrorLogGenerator_Test {
    @IsTest
    static void testError(){
        
        Test.startTest();
        DateTime logDate = datetime.newInstance(2021, 6, 21, 19, 30, 0);
        String logDetails = 'Error Test';
        String name = 'Test Error Name';
        ErrorLogGenerator.InsError(logDate, logDetails, name);

        Test.stopTest();
        Error_Log__c eLog = [Select Id, Log_Date_Tile__c, Log_Details__c, Process_Name__c from Error_Log__c];
        System.assertEquals('Test Error Name', eLog.Process_Name__c);
    }
}