objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <description>The recorded date and time of which when the event will end.</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>The recorded time and date of which when the event will start.</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>The assigned speaker for an event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>The event in which a speaker will talk.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>The speaker who is available to talk in an event.</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventSpeakerTrigger.cls
public with sharing class EventSpeakerTrigger {
    public static void getNamesFromEventSpeaker(List<Event_Speaker__c> ESList)
    {
        try{
    
            Set<Id> eventId = new Set<Id>();
            Set<Id> eventSpeakerId = new Set<Id>();

            for(Event_Speaker__c evntSpkr : ESList){
                eventId.add(evntSpkr.Event__c);
                eventSpeakerId.add(evntSpkr.Speaker__c);
            }
            
            Map<Id, DateTime> startrequestedEvents = new Map<Id, DateTime>();
            Map<Id, DateTime> endrequestedEvents = new Map<Id, DateTime>();

            List<Event__c> relatedEventList = [Select Id, Name,Start__c,End__c From Event__c 
            Where Id IN: eventId];

            for(Event__c evt : relatedEventList ){
                startrequestedEvents.put(evt.Id, evt.Start__c);
                endrequestedEvents.put(evt.Id, evt.End__c);
            
            }

            List<Event_Speaker__c> relatedEventSpeakerList = [ SELECT Id, Event__c, Speaker__c,Event__r.Start__c,Event__r.End__c From Event_Speaker__c
            WHERE Speaker__c IN : eventSpeakerId];

        for(Event_Speaker__c evntSpkr : ESList){

            DateTime startTime = startrequestedEvents.get(evntSpkr.Event__c);
            DateTime endTime = endrequestedEvents.get(evntSpkr.Event__c);


                for(Event_Speaker__c rS: relatedEventSpeakerList){
                    if((rS.Event__r.Start__c < endTime && rS.Event__r.End__c > endTime)||(rS.Event__r.Start__c < startTime && rS.Event__r.End__c > startTime)||(rS.Event__r.Start__c >= startTime && rS.Event__r.End__c <= endTime)){
                        evntSpkr.Speaker__c.addError('The Speaker has already an event!');
                    }

                }
        }
        }catch(Exception e){
            System.debug('Exceptions Handled: ' + e.getMessage());
        }
    }
}