objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <description>The recorded date and time of which when the event will end.</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to determine if the recorded event is currently live or not.</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of the recorded event.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateEventBatch.cls
public class UpdateEventBatch implements Database.Batchable<sObject> {
	
        public Database.QueryLocator start(Database.BatchableContext batchContext){
            String Query = 'Select Id, Name From Event__c Where Live__c = false AND Status__c != \'Completed\' AND End__c < LAST_N_MONTHS:4';
            return Database.getQueryLocator(Query);
        }
        
        public void execute(Database.BatchableContext bc, List<Event__c> eventList ){
                List<Event__c> updatedEventList = new List<Event__c>();
                for(Event__c event: eventList){
                    event.Status__c = 'Deleted';
                    updatedEventList.add(event);
                }
                update updatedEventList;
            
        }


        public void finish(Database.BatchableContext BC){
            
            AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                                TotalJobItems, CreatedBy.Email
                                FROM AsyncApexJob WHERE Id =
                                :BC.getJobId()];
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            String userName = UserInfo.getUserName();
            User activeUser = [Select Name,Email From User where Username = : userName limit 1];
            String userEmail = activeUser.Email;
            String userWholeName = activeUser.Name;
            
            
            mail.setSubject('Batch Processing Completed');
            List<String> toAddress = new List<String>();
            toAddress.add(userEmail);
            mail.setToAddresses( toAddress );
            mail.setSenderDisplayName(userWholeName);
            
            mail.setHtmlBody('The batch Apex job processed ' + a.TotalJobItems +
            ' batches with '+ a.NumberOfErrors + ' failures.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
         }
    }