objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <description>The recorded date and time of which when the event will end.</description>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>The recorded number of all the events.</description>
        <displayFormat>Event#-{0000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox to determine if the recorded event is currently live or not.</description>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>The recorded time and date of which when the event will start.</description>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>The assigned speaker for an event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>The event in which a speaker will talk.</description>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>The speaker who is available to talk in an event.</description>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventSpeakerTrigger_Test.cls
@isTest
private class EventSpeakerTrigger_Test {
    
    Static Id createTestEventID(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Start__c = datetime.newInstance(2021, 6, 27, 19, 30, 0);
        evt.End__c = datetime.newInstance(2021, 6, 28, 20, 30, 0);
        insert evt;
        return evt.Id;
    }
    Static Id createTestDupEventID(){
      Event__c evt = new Event__c();
      evt.Name = 'Test Dup Event';
      evt.Live__c = true;
      evt.Start__c = datetime.newInstance(2021, 6, 29, 19, 30, 0);
      evt.End__c = datetime.newInstance(2021, 6, 30, 20, 30, 0);
      insert evt;
      return evt.Id;
    }
    Static Id createSpeakerID(){
      Speaker__c spk = new Speaker__c();
      spk.Name = 'Test Speaker';
      insert spk;
      return spk.Id;
    }

        @IsTest
      Static void checkEventEspeaker(){
        Test.startTest();

        try{
          String spk = createSpeakerID();

        Event_Speaker__c eS = new Event_Speaker__c();
        //Field Names
        //Create a new data to object
        eS.Name = 'Test Event-Speaker';
        eS.Event__c = createTestEventID();
        eS.Speaker__c = spk;
        
        insert eS;
        
        Event_Speaker__c eSD = new Event_Speaker__c();
        eSD.Name = 'Test Dup Event-Speaker';
        eSD.Event__c = createTestEventID();
        eSD.Speaker__c = spk;
        
        insert eSD;

        

        
        Test.stopTest();
        Event_Speaker__c retrievedES = [Select Name from Event_Speaker__c where Name =: eSD.Name];
        System.assertEquals('Test Dup Event-Speaker',retrievedES.Name);
        
        }
        catch (Exception ex){
          System.debug('Get Exception: '+ex.getMessage());
        }
        
      }

    
}