objects/Location__c.object
<CustomObject>
    <description>Location or Address book of all the recorded Events using this app.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>The recorded City name for a potential event venue.</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Zip_correct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checks if the ZIP in the record inputted is correct using API</description>
        <label>Is Zip correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>The recorded Postal Code of an area that is a potential event venue.</description>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>The recorded State name for a potential event venue.</description>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The recorded Street names for a potential event venue.</description>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox determines if the selected location is verified as a event venue.</description>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LocationZipVerifierCallout.cls
public with sharing class LocationZipVerifierCallout {
    @future (callout=true)
    public static void verifyZip(String locId) {
        Location__c loc = [Select Id,Is_Zip_correct__c,State__c,Street__c,Postal_Code__c,City__c from Location__c where Id = :locId];

        Http httpzip = new Http();
        HttpRequest reqzip = new HttpRequest();
        String addzip = 'https://us-zipcode.api.smartystreets.com/lookup?auth-id=8e9ae4ae-97a2-35a9-a746-d8909c543101&auth-token=9jXkydJna30mfwvGWMPN&city=&state=&zipcode='+ +loc.Postal_Code__c;
        reqzip.setEndPoint(addzip);
        reqzip.setMethod('GET');
        HttpResponse respzip= new HttpResponse();
        respzip = httpzip.send(reqzip);


        try {
            if(respzip.getStatusCode() == 200){
                List<Object> resultsZipList = (List<Object>)JSON.deserializeUntyped(respzip.getBody());
                    for(Object obj : resultsZipList){
                        Map<String, Object> results = (Map<String, Object>) obj;
                        List<Object> zipObject = (List<Object>) results.get('zipcodes');
                        if(zipObject!=null){
                            loc.Is_Zip_correct__c = true;
                            update loc;
                            verifyLocation(locId);
                        }else{
                            loc.Is_Zip_correct__c = false;
                            update loc;
                        }
                
                    }
            } 
        
        }catch (Exception ex) {
            System.debug('Exception -- ' + ex.getMessage());
        }
    }
    
    public static void verifyLocation(String locId){
        Location__c loc = [Select Id,State__c,Street__c,Postal_Code__c,City__c, Ver__c, Is_Zip_correct__c from Location__c where Id = :locId];
        Http httpst = new Http();
        HttpRequest reqst = new HttpRequest();
         String addst = 'https://us-street.api.smartystreets.com/street-address?auth-id=8e9ae4ae-97a2-35a9-a746-d8909c543101&auth-token=9jXkydJna30mfwvGWMPN&'
         +'street=' + EncodingUtil.urlEncode(loc.Street__c, 'UTF-8') 
         +'&city='+ EncodingUtil.urlEncode(loc.City__c, 'UTF-8')
         +'&state='+EncodingUtil.urlEncode(loc.State__c, 'UTF-8');
         reqst.setEndPoint(addst);
         reqst.setMethod('GET');
        HttpResponse respst= new HttpResponse();
        respst = httpst.send(reqst); 
        try {
            if(respst.getStatusCode() == 200){
                String respstBody = respst.getBody();
                Integer zc;
                List<Object> resultsList = (List<Object>)JSON.deserializeUntyped(respst.getBody());
                for(Object obj : resultsList){
                    Map<String, Object> results = (Map<String, Object>) obj;
                    Map<String, Object> result = (Map<String, Object>)results.get('components');
                    zc = (Integer)integer.valueof(result.get('zipcode'));
                }
                    if(respstBody.length()>2 && zc==integer.valueof(loc.Postal_Code__c)){
                        
                        loc.Ver__c = true;
                    }else{
                        
                        loc.Ver__c = false;
                    }
                    update loc;
            }
        } 
        catch (Exception ex) {
            System.debug('Exception -- ' + ex.getMessage());
        }
    }

}